BEGIN;

-- 1. Crear categoria Frito Lay
INSERT INTO categorias (nombre, descripcion) VALUES ('Frito Lay', 'Productos Frito Lay') ON CONFLICT DO NOTHING;

-- 2. Listas de precios
INSERT INTO listasprecios (nombre) VALUES ('General') ON CONFLICT DO NOTHING;
INSERT INTO listasprecios (nombre) VALUES ('Mayorista') ON CONFLICT DO NOTHING;
BEGIN;
-- 3. Productos y precios
WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DETODITO BBQ X6', 900, 'https://drive.google.com/file/d/1j7uM1OVlwOr2CyuGvb7Qj7pRqHrjevIE/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),15000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),15000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DETODITO BBQ FAM', 900, 'https://drive.google.com/file/d/11yt606rXxU33Jak58dSyxTN13LKGi03d/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),7500.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),7500.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DETODITO BBQ BOLSAZA', 900, 'https://drive.google.com/file/d/1vzD0E-7qnpbLxToGYy0C-WxUK2stJgDl/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),3600.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),3600.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DETODITO NATURAL X12', 900, 'https://drive.google.com/file/d/1Tww8uKFElWW0O2_spZsjnjk0piOjQQEr/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),30000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),30000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DETODITO NATURAL X6', 900, 'https://drive.google.com/file/d/1CbjoB9sCSyyMM2wLCAHel11-IrUqiTlF/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),15000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),15000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DETODITO NATURAL FAM', 900, 'https://drive.google.com/file/d/1gXhoSV58q1klaUN-2fw21tMfNGcfRsXG/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),7500.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),7500.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DETODITO NATURAL BOLSAZA', 900, 'https://drive.google.com/file/d/1kZBv2IpNXjyedMZyHL6kN-nmiyBhZ2VK/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),3600.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),3600.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DETODITO MIX X12', 900, 'https://drive.google.com/file/d/1lBust1EdTMEaSwtJVwzHfQZ17gFdwXl7/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),30000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),30000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DETODITO MIX X6', 900, 'https://drive.google.com/file/d/1_xWpIWfxLG4qqRAORDwsN_-95hYn8b73/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),15000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),15000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DETODITO MIX FAM', 900, 'https://drive.google.com/file/d/1h6OYvF0_xeSpZ8qf2oNFl3Q28XEw1oUe/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),7500.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),7500.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DETODITO MIX BOLSAZA', 900, 'https://drive.google.com/file/d/18wi7aaCSArGj3C5D3RDk05foFlFSdTTo/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),3600.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),3600.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DETODTO LIMON X12', 900, 'https://drive.google.com/file/d/15-hHEtNYdALgQD8p7w62JaX4yo9AqGFp/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),30000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),30000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DETODITO LIMON X6', 900, 'https://drive.google.com/file/d/1Xwblorv7R8uqEfJm7qT36SyTRoCXfx4J/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),15000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),15000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DETODITO LIMON FAM', 900, 'https://drive.google.com/file/d/1tT-ZPdfKi1sWNPOyTXnsfhMdoLkM6gP3/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),7500.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),7500.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DETODITO POLLO X12', 900, 'https://drive.google.com/file/d/1PdWb_btqvVky1HWKf3j3FoR7jutw7D0i/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),30000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),30000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DETODITO POLLO X6', 900, 'https://drive.google.com/file/d/1sjEJ6Cvi8S-YdWttkhdJplc6_WK0igRC/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),15000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),15000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DETODITO FLAMING HOT X12', 900, 'https://drive.google.com/file/d/1HcJsaiD3dTQ9vb7V5QfETUESJ8-mmAkI/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),30000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),30000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DETODITO FLAMING HOT X6', 900, 'https://drive.google.com/file/d/1Bsgtt4YOn1X3UQ25wgw0su0mJXdi9Eig/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),15000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),15000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DORITOS X12', 900, 'https://drive.google.com/file/d/1Xe1BMeDIkvmxj5vbDwrNbJEKPDX3vSDW/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),26500.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),26500.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DORITOS X6', 900, 'https://drive.google.com/file/d/1kdW_ggbZedzM9sYS5k2SqucpCIAjPjqw/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),13300.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),13300.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DORITO FAM', 900, 'https://drive.google.com/file/d/1SIIodlbYgOZrlHQWKQihsLvFanIQ2KRh/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),7500.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),7500.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DORITO BOLSAZA', 900, 'https://drive.google.com/file/d/1PCn49VbD_xRIFQNPfF_V0crf14eJEHTp/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),3600.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),3600.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DINAMITA MORADO X12', 900, 'https://drive.google.com/file/d/12TRUYBCJZgu-1ANGS9iFYvisJMVozzRf/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),31200.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),31200.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DINAMITA MORADO X6', 900, 'https://drive.google.com/file/d/1WqU-tlTUL07UMOqZbNhqHlXMEc6J_8wZ/view?usp=drive_link', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),15600.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),15600.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DINAMITA LIMON X12', 900, 'https://drive.google.com/file/d/1pQ1kLYPri8KhXbAZwxL1_jv3ZHg_K4AK/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),31200.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),31200.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DINAMITA LIMON X6', 900, 'https://drive.google.com/file/d/12JKHxDhgpmB2Ai_makyJol4PQc1vZgyL/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),15600.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),15600.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DINAMITA SURTIDO X12', 900, 'https://drive.google.com/file/d/1MQuoO68It82He1PhlBHwpsSysLJvtNmt/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),31200.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),31200.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DINAMITA RULETA X12', 900, 'https://drive.google.com/file/d/1fXDN7TW7QRE5GFi7jUBAWy-b8WHGjJG9/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),31200.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),31200.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'DINAMITA RULETA X6', 900, 'https://drive.google.com/file/d/1_jV6SDQuJo2q7rVfg1NnX_DWlISGK7T2/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),15600.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),15600.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'NATUCHIPS MADURO X12', 900, 'https://drive.google.com/file/d/1FTitjN9KJfRSFrysmi7H0do33o1Iy1Bj/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),25000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),25000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'NATUCHIPS MADURO X6', 900, 'https://drive.google.com/file/d/1YDB_E9JTrpO4sFCkwpzTWl9xWsuSxVP6/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),12500.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),12500.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'NATUCHIPS SURTIDO X12', 900, 'https://drive.google.com/file/d/1lkEvUpA0-E-a2Xa3UXBYe9Yp3MvmgdXe/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),25000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),25000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'NATUCHIPS VERDE X12', 900, 'https://drive.google.com/file/d/1_ZuIF7oToFYZJg1yFiSDuK7SznpVgo6V/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),25000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),25000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'NATUCHIPS VERDE X6', 900, 'https://drive.google.com/file/d/1F1qZMR-fZjo0rAuB3HhBPfjLMTYrZIhH/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),12500.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),12500.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'NATUCHIPS YUCA X12', 900, 'https://drive.google.com/file/d/1qCm5m17sdQRpaHYmb8y5iuPcHopiY3EH/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),25000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),25000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'NATUCHIPS YUCA X6', 900, 'https://drive.google.com/file/d/1Y4eTI_Etc1wavlqXvDcvXAIoQEUckmO7/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),12500.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),12500.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'NATUCHIPS MADURO FAM', 900, 'https://drive.google.com/file/d/1baRsfSv9y3CfT3TQXyTYmXJyVL6YPEfP/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),6500.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),6500.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'NATUCHIPS VERDE FAM', 900, 'https://drive.google.com/file/d/16WF68CSAlxzQR44M4OC31032rvH_pGbF/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),6500.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),6500.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'PAPA LIMON X25G X 12', 900, 'https://drive.google.com/file/d/1snziReEk_lYiDtV8qH1r9Aii58nHmAI_/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),19000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),19000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'PAPA LIMON FAM', 900, 'https://drive.google.com/file/d/1JGuu5S2-GbmjZROAYuzItr6xt8jL4T7S/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),6100.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),6100.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'PAPA LIMON BOLSAZA', 900, 'https://drive.google.com/file/d/1fkaP7P_y93h_4fExfQQayhIBcel-PqTG/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),3600.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),3600.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'PAPA NATURAL X25G X 12', 900, 'https://drive.google.com/file/d/1tIFFNGo60m5v5PrBC6vz2i1KCTi0PP68/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),19000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),19000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'PAPA NATURAL FAM', 900, 'https://drive.google.com/file/d/1-iUtEw6P_IAX8THgPh4v0hINdREX_8ke/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),6100.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),6100.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'PAPA POLLO X25G X 12', 900, 'https://drive.google.com/file/d/1rpl0R588UhkYf7bnEAJPMaDlfG0cRqDw/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),19000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),19000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'PAPA POLLO FAM', 900, 'https://drive.google.com/file/d/1cAd_ZyKrV7lEmluzHnP7G-Wguaqw6ovn/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),6100.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),6100.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'PAPA POLLO BOLSAZA', 900, 'https://drive.google.com/file/d/1vJz66WmBckQrSMA4qNiiS0VhKGJTE0vw/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),3600.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),3600.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'PAPA OND TOMATE X12', 900, 'https://drive.google.com/file/d/168Kqyxy0WkCaz7KR-uHmwEQehUMClmTE/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),25000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),25000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'PAPA OND TOMATE X6', 900, 'https://drive.google.com/file/d/1jbKB4qVTDQtq7RZEwyRPScXfIkkYDcTb/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),12500.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),12500.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'PAPA OND TOMATE FAM', 900, 'https://drive.google.com/file/d/1-f148yl7pAZWfyCm4jvhA1kHemnf3hvj/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),6100.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),6100.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'PAPA OND SURTIDA X12', 900, 'https://drive.google.com/file/d/1RZh3z5OR0JVtWHPrCtWLJq7kuQpn2Ptl/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),25000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),25000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'PAPA OND MAYONESA X12', 900, 'https://drive.google.com/file/d/1QzTTY84X8aDzixQJyqwsdu7PC11J36X9/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),25000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),25000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'PAPA OND MAYONESA X6', 900, 'https://drive.google.com/file/d/1g0GwVkFCfs-lKcpne4sTZUmPE0mEPeev/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),12500.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),12500.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'PAPA OND MAYONESA FAM', 900, 'https://drive.google.com/file/d/1RyItzTcbUclEe04zV_qt5Q5wFibeZcv7/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),6100.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),6100.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'PAPA CHORIZO LIMON X12', 900, 'https://drive.google.com/file/d/17s_adXopbE1zERoVZjmPf5ndhjynuSZ1/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),25000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),25000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'PAPA CHORIZO LIMON X6', 900, 'https://drive.google.com/file/d/1PJaryrbAPYoVKvVQ04O-8I5PCv9NGPGf/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),12500.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),12500.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'PAPA CREMA Y CEBOLLA X12', 900, 'https://drive.google.com/file/d/1gaugfQo268gGPwR1vOvM4Z15JcE9PWje/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),25000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),25000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'PAPA CREMA Y CEBOLLA X6', 900, 'https://drive.google.com/file/d/1d5wWCro2VoW8t-1LlSCKRmLUNKilf3Q3/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),12500.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),12500.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'PAPA BBQ X12', 900, 'https://drive.google.com/file/d/1KSWRPxDf-ZZqZEAnyb3ySFmHjTvFbsrA/view?usp=drive_link', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),19000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),19000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'CHEESE TRIS QUESO X12', 900, 'https://drive.google.com/file/d/1_m0XCghDEQVC7prHLIji46m1qMigJnLW/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),21600.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),21600.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'CHEESE TRIS QUESO FAM', 900, 'https://drive.google.com/file/d/1lgd-um045PMTz77L9pJy4KPEMoyryejC/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),3600.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),3600.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'CHOCLITO LIMON X12', 900, 'https://drive.google.com/file/d/1miQQNBF418RRr7QOguuuQRyw2Cwgh1LT/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),21600.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),21600.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'CHOCLITO LIMON BOLSAZA', 900, 'https://drive.google.com/file/d/1xxJIsvXUYR5XIoDnqtLtrhjyr7Ul55OA/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),3600.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),3600.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'CHOCLITO LIMON FAM', 900, 'https://drive.google.com/file/d/1VEBPce1_nzrsu9JszzezrC0ssv_yMLaF/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),7000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),7000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'CHOCLITO PICANTE X12', 900, 'https://drive.google.com/file/d/1JxaBeHaPyY_qq5JuutA0R7_zx0cmoTtn/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),21600.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),21600.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'CHEETOS BOLIQUESO X12', 900, 'https://drive.google.com/file/d/1bq1oTy96H6Iv-WlTNJYHf_67zDOoUT_B/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),12500.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),12500.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'CHEETOS BOLIQUESO 34G', 900, 'https://drive.google.com/file/d/1qNN5l8-lZqa20UKXZY8bD76yPFI5xcyS/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),1800.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),1800.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'CHEETOS BOLIQUESO FAM', 900, 'https://drive.google.com/file/d/1j_7NgMHAR4diBfArps3qT4YY8FrWzpXk/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),6500.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),6500.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'GUDIZ VAINILLA X12', 900, 'https://drive.google.com/file/d/1xy3O0fV3FFt3-lXXKb8Ju3FMAeK058vo/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),12500.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),12500.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'SUPER LONCHERA X12', 900, 'https://drive.google.com/file/d/1WkudMcDTc7uD1h-V5fD_TK7SFV3TosVQ/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),12000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),12000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'MEGA LONCHERA X22', 900, 'https://drive.google.com/file/d/1a6_z-rBXSmD_tykJhqnRwjkBZ8nFBD8O/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),22500.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),22500.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'CHOKIS CHISPA AZUL X6', 900, 'https://drive.google.com/file/d/1bykx6fJ7YEKB8eo8xPkU67Cf0R3ADGEn/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),8000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),8000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'CHOKIS CHOCOBASE ROJA X6', 900, 'https://drive.google.com/file/d/1gNvilXbGKI2nTpRFnml_K8mFaSjO3BTg/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),8000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),8000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'CHOKIS BLACK X6', 900, 'https://drive.google.com/file/d/1sH_aH5A2ogLJ-HRpx7qAnwCsRYKASGhh/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),8000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),8000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'CHOKIS CHOCOLATE BOLITA X16', 900, 'https://drive.google.com/file/d/19mY10G3wfCAwY3a8ThVlngpaLufZTm_0/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),20400.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),20400.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'QUAKER MANZANA CANELA X6', 900, 'https://drive.google.com/file/d/1HkoJmScLRZT00hochWMzehWVajynMnV7/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),7500.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),7500.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'QUAKER FRUTOS ROJOS X6', 900, 'https://drive.google.com/file/d/1GVyQ3to42RbrQpTBmzs_B5mGtNqfPfGI/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),7500.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),7500.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'QUAKER PASAS X6', 900, 'https://drive.google.com/file/d/1T0bACg4EecnVW-ptKCodAdFhvhxLj0M4/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),7500.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),7500.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'QUAKER GRANOLA X6', 900, 'https://drive.google.com/file/d/1dLoCbknjmlq5qoBNpCz3edWsYuNnlLWS/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),7500.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),7500.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'MAMUT BLANCO X42', 900, 'https://drive.google.com/file/d/1DByICW7fLZIDJD8tolKDtDGMp2F1lxGo/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),18100.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),18100.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'MAMUT OSCURO X42', 900, 'https://drive.google.com/file/d/1nv68jFcaq1ei9hzbt_xfFEYBLvur35Oo/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),18100.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),18100.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'MANI MOTO NATURAL X12', 900, 'https://drive.google.com/file/d/1zJNIV6AWbjWSK2s6U5kdP2QYxcjPnRlX/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),17000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),17000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'MANI MOTO LIMON X12', 900, 'https://drive.google.com/file/d/1CfVq4V3rlaX1Ohcu2VBo5CiwPw64J92S/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),17000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),17000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'MANI MOTO FLAMING HOT X12', 900, 'https://drive.google.com/file/d/1ch7emtuG2et0MNy85sEq23V_2MmFVyH8/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),17000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),17000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'MANI MOTO NATURAL 80G X9', 900, 'https://drive.google.com/file/d/1iLJqp0zGVRc3a368RzR2c6ideGyalFQh/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),16300.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),16300.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'MANI MOTO NAKED PASAS X36G', 900, 'https://drive.google.com/file/d/1CU7BpXQqkZYJvAg_11rVNSoZuHq54Y4t/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),15600.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),15600.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'MANI MOTO NAKED SAL X23G', 900, 'https://drive.google.com/file/d/17CMwmC0J3S5wJ5Pi6lAOu1u0oh5j6Mm6/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),21600.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),21600.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'MANI MOTO NAKED SAL X36G', 900, 'https://drive.google.com/file/d/1G8nIZMV-Ppix6TZGRyY75ehtzPxG0Egq/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),15600.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),15600.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'CHEETO NATURAL ', 900, 'https://drive.google.com/file/d/1m9actFLjMRHu6VUoymYaziiKytGk3scb/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),1800.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),1800.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'CHEETO PICANTE', 900, 'https://drive.google.com/file/d/1Hj9uwQ0Pf-x5do-GwxYYhVj6LmbO7WnL/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),1800.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),1800.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'MANI MOTO 180G', 900, 'https://drive.google.com/file/d/1S1UVpxRZyhTmmisZ9pL0iBUDqu5dm9A3/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),5000.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),5000.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'MANI SALADO 200G', 900, 'https://drive.google.com/file/d/1XE_XDAp1oBC66x19U9XFj6DtlHXpej5-/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),5500.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),5500.0 FROM np;

WITH np AS (INSERT INTO productos (nombre, stock, imagen_url, categoria_id) SELECT 'MANI CON PASAS 200G', 900, 'https://drive.google.com/file/d/1wtVCvXkZbFl-sfdy5hflEvcFwhzha9cH/view?usp=sharing', (SELECT id FROM categorias WHERE nombre='Frito Lay' LIMIT 1) RETURNING id)INSERT INTO precios (producto_id, lista_id, precio) SELECT id,(SELECT id FROM listasprecios WHERE nombre='General' LIMIT 1),5500.0 FROM np UNION ALL SELECT id,(SELECT id FROM listasprecios WHERE nombre='Mayorista' LIMIT 1),5500.0 FROM np;

COMMIT;